apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: galaxiasneural-net-tls
spec:
  secretName: galaxiasneural-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: galaxiasneural.net
  dnsNames:
    - galaxiasneural.net
    - www.galaxiasneural.net
  acme:
    config:
      - http01: 
          ingressClass: nginx
        domains:
          - galaxiasneural.net
          - www.galaxiasneural.net